import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { cp, mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { randomBytes } from 'node:crypto';
import { join, resolve } from 'node:path';
import { createServer } from 'node:http';
import { once } from 'node:events';
import { captureVisiblePage } from '../dist/packages/observation/src/dom.js';
import { verificationServer } from '../dist/packages/agent-runtime/src/server.js';
import { replay } from '../dist/packages/reasoning-core/src/core.js';
import { reproduce } from '../dist/packages/verifier/src/index.js';

// Isolated test installation: grant optional loopback access up front. The production
// manifest remains unchanged. Native toolbar activation/permission dialogs have a manual checklist.
const dir = await mkdtemp(join(tmpdir(), 'logosphere-browser-test-'));
const extension = join(dir, 'extension'); await cp(resolve('dist/extension'), extension, { recursive: true });
const manifest = JSON.parse(await readFile(join(extension, 'manifest.json'), 'utf8'));
manifest.host_permissions = ['http://127.0.0.1/*'];
await writeFile(join(extension, 'manifest.json'), JSON.stringify(manifest));
const token = randomBytes(32).toString('hex');
const bridgeOptions = { token, port: 4318, allowedOrigin: '' };
const verifier = verificationServer(bridgeOptions);
const fixtureHtml = await readFile('fixtures/argument.html', 'utf8');
const fixture = createServer((_request, response) => { response.writeHead(200, { 'Content-Type': 'text/html' }); response.end(fixtureHtml); });
let context;
try {
  verifier.listen(4318, '127.0.0.1'); await once(verifier, 'listening');
  fixture.listen(0, '127.0.0.1'); await once(fixture, 'listening');
  context = await chromium.launchPersistentContext(join(dir, 'profile'), { channel: 'chromium', headless: true, viewport: { width: 1100, height: 900 }, args: [`--disable-extensions-except=${extension}`, `--load-extension=${extension}`] });
  const manager = await context.newPage(); await manager.goto('chrome://extensions/');
  const installed = await manager.evaluate(() => new Promise(resolveInfo => chrome.developerPrivate.getExtensionsInfo({ includeDisabled: true, includeTerminated: true }, resolveInfo)));
  const info = installed.find(item => item.name.startsWith('Logosphere'));
  assert.ok(info, `Extension failed to load: ${JSON.stringify(installed)}`);
  const extensionId = info.id; bridgeOptions.allowedOrigin = `chrome-extension://${extensionId}`;
  await manager.close();
  const source = await context.newPage();
  await source.goto(`http://127.0.0.1:${fixture.address().port}/argument.html?private=omitted#fragment`);
  const captured = await source.evaluate(captureVisiblePage);
  assert.ok(captured.text.includes('Therefore:')); assert.ok(!/PRIVATE_FORM_SENTINEL|HIDDEN_SENTINEL|EDITABLE_SENTINEL/.test(captured.text));
  assert.ok(!captured.url.includes('private='));
  const popup = await context.newPage(); const errors = [];
  const worker = context.serviceWorkers()[0] ?? await context.waitForEvent('serviceworker');
  const sourceTabId = await worker.evaluate(async url => {
    // tabs.query URL filters are match patterns, not exact URLs with fragments.
    const tabs = await chrome.tabs.query({});
    const sourceTab = tabs.find(tab => tab.url === url);
    if (sourceTab?.id === undefined) throw new Error('Synthetic source tab is unavailable to the test extension');
    return sourceTab.id;
  }, source.url());
  popup.on('pageerror', error => errors.push(error.message));
  await popup.goto(`chrome-extension://${extensionId}/popup.html?sourceTab=${sourceTabId}`);
  assert.equal(await popup.locator('#input').inputValue(), '');
  await popup.locator('#capture').click();
  await popup.getByRole('status').filter({ hasText: 'Capture complete' }).waitFor();
  assert.equal(await popup.locator('#input').inputValue(), captured.text);
  await popup.locator('#preview').click();
  await popup.getByRole('status').filter({ hasText: 'Candidate graph ready' }).waitFor();
  assert.equal(await popup.locator('.edge').count(), 1);
  await popup.locator('#accept').click(); await popup.getByRole('status').filter({ hasText: 'Graph created' }).waitFor();
  await popup.getByText('Connect a local Lean verifier', { exact: true }).click();
  await popup.locator('#token').fill(token); await popup.locator('#verify').click();
  await popup.getByRole('status').filter({ hasText: 'Local verification completed' }).waitFor({ timeout: 30_000 });
  assert.match(await popup.locator('.edge > strong').innerText(), /^PROVEN/);
  assert.match(await popup.locator('.assumption > strong').innerText(), /ASSUMPTION/);
  assert.match(await popup.locator('.premise > strong').innerText(), /UNRESOLVED/);
  await source.bringToFront(); await popup.bringToFront();
  assert.match(await popup.locator('.edge > strong').innerText(), /^PROVEN/);
  await mkdir('artifacts', { recursive: true });
  await popup.screenshot({ path: 'artifacts/extension-preview.png', fullPage: true });
  const downloadPromise = popup.waitForEvent('download'); await popup.locator('#export').click();
  const download = await downloadPromise; const exportedPath = resolve('artifacts/browser-export.json'); await download.saveAs(exportedPath);
  const graph = await replay(JSON.parse(await readFile(exportedPath, 'utf8')));
  assert.equal(graph.verifications.size, 1);
  const receipt = [...graph.verifications.values()][0].value;
  assert.equal((await reproduce(graph, receipt.id)).matches, true);
  await popup.locator('#clear').click();
  await popup.locator('#import').setInputFiles(exportedPath);
  await popup.getByRole('status').filter({ hasText: 'Artifact integrity checked' }).waitFor();
  assert.match(await popup.locator('.edge > strong').innerText(), /^UNVERIFIED/);
  assert.match(await popup.locator('.edge').innerText(), /Reported receipt: PROVEN/);
  await popup.reload(); assert.equal(await popup.locator('.node').count(), 0);
  assert.deepEqual(errors, []);
  console.log('PASS: actual Capture button and source-tab binding; focus changes preserve graph; extension preview/accept; actual loopback Lean verification; export and independent proof reproduction; imported-status downgrade; session forgetting.');
  console.log('Native toolbar activation and permission prompts are separate manual release checks. Test profile used pregranted loopback access.');
} finally {
  await context?.close();
  verifier.closeAllConnections(); fixture.closeAllConnections();
  await Promise.all([new Promise(resolveClose => verifier.close(resolveClose)), new Promise(resolveClose => fixture.close(resolveClose))]);
  await rm(dir, { recursive: true, force: true });
}
